### ISSUE TITLE
Error on release with no unreleased changelogs

### ISSUE THREAD

**Issue by jbghoul** [wanadev/changelogify#17]
Release should not throw an error if there's no changelogs. 
Il should only add a new version line un CHANGELOG.md with no change

```
{ Error: ENOENT: no such file or directory, scandir '/home/jbghoul/dev/kazaplan-plugin-model-thumbnailer/changelogs/unreleased/'
    at Object.readdirSync (fs.js:790:3)
    at Command.release (/home/jbghoul/dev/kazaplan-plugin-model-thumbnailer/node_modules/changelogify/index.js:211:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path:
   '/home/jbghoul/dev/kazaplan-plugin-model-thumbnailer/changelogs/unreleased/' }
```

**Comment by robincartier** [comment]
@jbghoul you can test the fix

**Comment by jbghoul** [comment]
Still throw error with autoCommitRelease:true

```
$ npm run changelog -- release -s

> kazaplan-plugin-api-user@3.64.0 changelog /home/jbghoul/dev/kazaplan-plugin-api-user
> node node_modules/changelogify/index.js "release" "-s"

Error: fatal: le chemin '/home/jbghoul/dev/kazaplan-plugin-api-user/changelogs/unreleased/' ne correspond à aucun fichier

    at toError (/home/jbghoul/dev/kazaplan-plugin-api-user/node_modules/simple-git/promise.js:90:14)
    at /home/jbghoul/dev/kazaplan-plugin-api-user/node_modules/simple-git/promise.js:61:36
    at Git.<anonymous> (/home/jbghoul/dev/kazaplan-plugin-api-user/node_modules/simple-git/src/git.js:270:18)
    at Function.Git.fail (/home/jbghoul/dev/kazaplan-plugin-api-user/node_modules/simple-git/src/git.js:1475:18)
    at fail (/home/jbghoul/dev/kazaplan-plugin-api-user/node_modules/simple-git/src/git.js:1433:20)
    at /home/jbghoul/dev/kazaplan-plugin-api-user/node_modules/simple-git/src/git.js:1442:16
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
